#Databse
spring.datasource.url=jdbc:postgresql://localhost:5432/carbon_tracker
spring.datasource.username=postgres
spring.datasource.password=deepika
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google
spring.security.oauth2.client.registration.google.client-id=563421885687-rc8pv81o8ntkgkic76uecndt5dklong4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
# GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23lioOelQzOqMCGDcH
spring.security.oauth2.client.registration.github.client-secret=8e6f88c01bfc166028cb240bd46719611d220114

# Mail - send OTP by email (forgot password)
app.mail.enabled=true
app.mail.from=deepikavish095@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deepikavish095@gmail.com
spring.mail.password=zvkbpywpfpinllhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true   
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true


