# ===============================
# PostgreSQL Database Configuration
# ===============================
# Edit password if your PostgreSQL uses something other than "root"

spring.datasource.url=jdbc:postgresql://localhost:5432/carbontracker
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OAuth (required for startup)
spring.security.oauth2.client.registration.google.client-id=674731609729-ipd2dspp0ecukgj2pdku1a0m3ket42ej.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.github.client-id=Ov23lioOelQzOqMCGDcH
spring.security.oauth2.client.registration.github.client-secret=8e6f88c01bfc166028cb240bd46719611d220114

# Mail (forgot password OTP)
app.mail.enabled=true
app.mail.from=s22_tarpe_akshay@mgmcen.ac.in
app.mail.from.name=CarbonCalc
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=s22_tarpe_akshay@mgmcen.ac.in
spring.mail.password=tzlq gqtq csye sqdf
